# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_title',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
